# Generated by Django 5.0.1 on 2024-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zacapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
