# Generated by Django 5.0.1 on 2024-01-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zacapp', '0002_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amountpaid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_signature',
        ),
    ]
