# Generated by Django 5.0.1 on 2024-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zacapp', '0003_remove_orders_amountpaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='The order has been placed', max_length=5000),
        ),
    ]
