# Generated by Django 5.0.1 on 2024-02-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zacapp', '0006_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='OrderPlaced', max_length=5000),
        ),
    ]
