# Generated by Django 5.0.1 on 2024-02-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zacapp', '0007_alter_orderupdate_update_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
