# Generated by Django 5.0.1 on 2024-02-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zacapp', '0009_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
