# Generated by Django 5.0.1 on 2024-02-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zacapp', '0010_cart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
    ]
